"""empty message

Revision ID: 8c2ec8db472c
Revises: 
Create Date: 2024-03-20 01:03:22.089510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2ec8db472c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_title', sa.String(length=120), nullable=True),
    sa.Column('prop_description', sa.String(length=1000), nullable=True),
    sa.Column('prop_rooms', sa.Integer(), nullable=True),
    sa.Column('prop_bathrooms', sa.Integer(), nullable=True),
    sa.Column('prop_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prop_type', sa.Enum('house', 'apartment', name='propertytype'), nullable=True),
    sa.Column('prop_location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_profiles')
    # ### end Alembic commands ###
